global:
  environment: dev
  logLevel: debug

servicio-autenticacion:
  replicaCount: 1

servicio-catalogo:
  replicaCount: 1

servicio-pedidos:
  replicaCount: 1

servicio-pagos:
  replicaCount: 1

api-gateway:
  replicaCount: 1
