global:
  namespace: sa-p8
  environment: prod
  logLevel: info
  imagePullPolicy: IfNotPresent

  labels:
    course: software-avanzado
    practice: practica-8

servicio-autenticacion:
  image:
    repository: kvnslz/sa-p8-auth
    tag: v1.0.3

servicio-catalogo:
  image:
    repository: kvnslz/sa-p8-catalogo
    tag: v1.0.3

servicio-pedidos:
  image:
    repository: kvnslz/sa-p8-pedidos
    tag: v1.0.3

servicio-pagos:
  image:
    repository: kvnslz/sa-p8-pagos
    tag: v1.0.3

api-gateway:
  image:
    repository: kvnslz/sa-p8-gateway
    tag: v1.0.3

  service:
    type: LoadBalancer
    port: 3007

cronjobs:
  image:
    repository: kvnslz/sa-p8-cronjobs
    tag: v1.0.3
    pullPolicy: IfNotPresent

postgresql:
  persistence:
    storageClassName: gp3
    size: 1Gi

rabbitmq:
  persistence:
    storageClassName: gp3
    size: 1Gi
