global:
  environment: prod
  logLevel: info


servicio-autenticacion:
  replicaCount: 1

  image:
    tag: v1

  resources:
    limits:
      cpu: 400m
      memory: 384Mi


servicio-catalogo:
  replicaCount: 1

  image:
    tag: v1

  resources:
    limits:
      cpu: 400m
      memory: 384Mi


servicio-pedidos:
  replicaCount: 1

  image:
    tag: v1

  resources:
    limits:
      cpu: 400m
      memory: 384Mi


servicio-pagos:
  replicaCount: 1

  image:
    tag: v1

  resources:
    limits:
      cpu: 400m
      memory: 384Mi


api-gateway:
  replicaCount: 1

  image:
    tag: v1

  resources:
    limits:
      cpu: 400m
      memory: 384Mi
