apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "sa-platform.fullname" . }}-config
  namespace: {{ required "Debe definir global.namespace" .Values.global.namespace }}

  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}

data:
  ENVIRONMENT: {{ default "dev" .Values.global.environment | quote }}
  LOG_LEVEL: {{ default "info" .Values.global.logLevel | quote }}

  DB_HOST: {{ .Values.global.config.database.host | quote }}
  DB_PORT: {{ .Values.global.config.database.port | quote }}
  DB_NAME: {{ .Values.global.config.database.name | quote }}
  DB_USER: {{ .Values.global.config.database.user | quote }}

  # Broker RabbitMQ
  RABBITMQ_HOST: {{ .Values.global.config.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.global.config.rabbitmq.port | quote }}
  RABBITMQ_QUEUE: {{ .Values.global.config.rabbitmq.queue | quote }}

  FRONTEND_URL: {{ .Values.global.config.frontendUrl | quote }}

  JWT_EXPIRES_IN_SECONDS: {{ .Values.global.config.jwt.expiresInSeconds | quote }}
  JWT_RENEWAL_GRACE_SECONDS: {{ .Values.global.config.jwt.renewalGraceSeconds | quote }}

  AUTH_PORT: {{ .Values.global.config.ports.auth | quote }}
  CATALOGO_PORT: {{ .Values.global.config.ports.catalogo | quote }}
  PEDIDOS_PORT: {{ .Values.global.config.ports.pedidos | quote }}
  PAGOS_PORT: {{ .Values.global.config.ports.pagos | quote }}
  GATEWAY_PORT: {{ .Values.global.config.ports.gateway | quote }}

  AUTH_SERVICE_URL: {{ .Values.global.config.services.authUrl | quote }}
  CATALOGO_SERVICE_URL: {{ .Values.global.config.services.catalogoUrl | quote }}
  PEDIDOS_SERVICE_URL: {{ .Values.global.config.services.pedidosUrl | quote }}
  PAGOS_SERVICE_URL: {{ .Values.global.config.services.pagosUrl | quote }}

  {{- if eq .Values.global.environment "prod" }}
  PRODUCTION_MODE: "true"
  {{- else }}
  PRODUCTION_MODE: "false"
  {{- end }}

  CRON_STUDENT_ID: {{ .Values.global.config.cron.studentId | quote }}
  RABBITMQ_CRON_QUEUE: {{ .Values.global.config.cron.summaryQueue | quote }}