apiVersion: v1
kind: Service

metadata:
  name: servicio-pedidos
  namespace: {{ .Values.global.namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: servicio-pedidos

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
