apiVersion: v1
kind: Service

metadata:
  name: servicio-pedidos-canary
  namespace: {{ .Values.global.namespace }}

  labels:
    app: servicio-pedidos
    role: canary

spec:
  type: ClusterIP

  selector:
    app: servicio-pedidos

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
