apiVersion: v1
kind: Service

metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: api-gateway

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
