apiVersion: v1
kind: Service

metadata:
  name: rabbitmq-headless
  namespace: {{ .Values.global.namespace }}

  labels:
    app: rabbitmq

spec:
  clusterIP: None

  selector:
    app: rabbitmq

  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: amqp
