apiVersion: v1
kind: Service

metadata:
  name: rabbitmq
  namespace: {{ .Values.global.namespace }}

  labels:
    app: rabbitmq

spec:
  type: ClusterIP

  selector:
    app: rabbitmq

  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: amqp

    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
